version: 0.2


phases:
  build:
    commands:
      - echo Entered the build phase...
      - apt-get update -y
      - sudo apt install nodejs
      - sudo apt install npm
      - npm install -g aws-cdk
      - cdk version
    finally:
      - echo This always runs even if the install command fails

artifacts:
  files:
    - "**/*"

